/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author shofwan as
 */
public class FormPemesanan extends javax.swing.JFrame {
    private int totalBayar = 0;
    private static final int HARGA_STEAK = 50000;
    private static final int HARGA_SPAGHETI = 35000;
    private static final int HARGA_PIZZA = 850000;
    /**
     * Creates new form FormPemesanan
     */
    public FormPemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTItle = new java.awt.Label();
        DataCustomer = new javax.swing.JPanel();
        Nama = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        NoTelp = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        AlamatField = new javax.swing.JTextField();
        NoTelpField = new javax.swing.JTextField();
        PilihMenu = new javax.swing.JPanel();
        Steak = new javax.swing.JCheckBox();
        Spagheti = new javax.swing.JCheckBox();
        Pizza = new javax.swing.JCheckBox();
        HargaSteak = new javax.swing.JLabel();
        HargaSpagheti = new javax.swing.JLabel();
        HargaPiza = new javax.swing.JLabel();
        TotalBayar = new javax.swing.JLabel();
        TotBayar = new javax.swing.JTextField();
        ButtonTambah = new javax.swing.JButton();
        DataPesananPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataPesanan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pemesanan Makanan");

        LabelTItle.setAlignment(java.awt.Label.CENTER);
        LabelTItle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        LabelTItle.setText("APLIKASI PEMESANAN");

        DataCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Customer"));
        DataCustomer.setName("DataCustomer"); // NOI18N

        Nama.setText("Nama:");

        Alamat.setText("Alamat:");

        NoTelp.setText("NoTelp:");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataCustomerLayout = new javax.swing.GroupLayout(DataCustomer);
        DataCustomer.setLayout(DataCustomerLayout);
        DataCustomerLayout.setHorizontalGroup(
            DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataCustomerLayout.createSequentialGroup()
                        .addComponent(Nama)
                        .addGap(18, 18, 18)
                        .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(DataCustomerLayout.createSequentialGroup()
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alamat)
                            .addComponent(NoTelp))
                        .addGap(12, 12, 12)
                        .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoTelpField)
                            .addComponent(AlamatField))))
                .addContainerGap())
        );
        DataCustomerLayout.setVerticalGroup(
            DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamat)
                    .addComponent(AlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoTelp)
                    .addComponent(NoTelpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PilihMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Menu"));
        PilihMenu.setName("PilihMenu"); // NOI18N

        Steak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Steak.setLabel("Steak");
        Steak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SteakActionPerformed(evt);
            }
        });

        Spagheti.setText("Spagheti");
        Spagheti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Spagheti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaghetiActionPerformed(evt);
            }
        });

        Pizza.setText("Pizza");
        Pizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaActionPerformed(evt);
            }
        });

        HargaSteak.setText("Rp. 50.000,-");

        HargaSpagheti.setText("Rp. 35.000,-");

        HargaPiza.setText("Rp. 85.000,-");

        javax.swing.GroupLayout PilihMenuLayout = new javax.swing.GroupLayout(PilihMenu);
        PilihMenu.setLayout(PilihMenuLayout);
        PilihMenuLayout.setHorizontalGroup(
            PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PilihMenuLayout.createSequentialGroup()
                        .addComponent(Steak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HargaSteak))
                    .addGroup(PilihMenuLayout.createSequentialGroup()
                        .addGroup(PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Spagheti)
                            .addComponent(Pizza))
                        .addGap(18, 18, 18)
                        .addGroup(PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HargaPiza)
                            .addComponent(HargaSpagheti))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PilihMenuLayout.setVerticalGroup(
            PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Steak)
                    .addComponent(HargaSteak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spagheti)
                    .addComponent(HargaSpagheti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PilihMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pizza)
                    .addComponent(HargaPiza))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TotalBayar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TotalBayar.setText("TOTAL BAYAR");

        TotBayar.setBackground(new java.awt.Color(0, 0, 0));
        TotBayar.setForeground(new java.awt.Color(204, 204, 0));
        TotBayar.setToolTipText("");
        TotBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotBayarActionPerformed(evt);
            }
        });

        ButtonTambah.setText("TAMBAH");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        DataPesananPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("DataPesanan"));

        DataPesanan.setEditable(false);
        DataPesanan.setColumns(20);
        DataPesanan.setRows(5);
        DataPesanan.setToolTipText("");
        jScrollPane1.setViewportView(DataPesanan);

        javax.swing.GroupLayout DataPesananPanelLayout = new javax.swing.GroupLayout(DataPesananPanel);
        DataPesananPanel.setLayout(DataPesananPanelLayout);
        DataPesananPanelLayout.setHorizontalGroup(
            DataPesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        DataPesananPanelLayout.setVerticalGroup(
            DataPesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonTambah)
                            .addComponent(TotBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalBayar)
                                    .addComponent(PilihMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(DataPesananPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelTItle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTItle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PilihMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonTambah)
                .addGap(18, 18, 18)
                .addComponent(DataPesananPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        String name = "Nama: " + NameField.getText() + "\n";
        String address = "Alamat: " + AlamatField.getText() + "\n";
        String phone = "Telp: " + NoTelpField.getText() + "\n";
        
        if(!Steak.isSelected() && !Spagheti.isSelected() && !Pizza.isSelected()){
            JOptionPane.showMessageDialog(this, "Belum ada menu yg dipilih!");
            DataPesanan.setText("");
            return;
        }
        
        String data = name + address + phone + "=================\n";
        if(Steak.isSelected()){
            data += "   - " + Steak.getText() + "\n";
        }
        if(Spagheti.isSelected()){
            data += "   - " + Spagheti.getText() + "\n";
        }
        if(Pizza.isSelected()){
            data += "   - " + Pizza.getText() + "\n";
        }
        data += "=================\n" + "Total Bayar:\n   RP. " + totalBayar;
        
        DataPesanan.setText(data);
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void SteakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SteakActionPerformed
        // TODO add your handling code here:
        if(Steak.isSelected()){
            totalBayar += HARGA_STEAK;
        }
        else{
            totalBayar -= HARGA_STEAK;
        }
        TotBayar.setText(String.valueOf(totalBayar));
    }//GEN-LAST:event_SteakActionPerformed

    private void TotBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotBayarActionPerformed

    private void SpaghetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaghetiActionPerformed
        // TODO add your handling code here:
        if(Spagheti.isSelected()){
            totalBayar += HARGA_SPAGHETI;
        }
        else{
            totalBayar -= HARGA_SPAGHETI;
        }
        TotBayar.setText(String.valueOf(totalBayar));
    }//GEN-LAST:event_SpaghetiActionPerformed

    private void PizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaActionPerformed
        // TODO add your handling code here:
        if(Pizza.isSelected()){
            totalBayar += HARGA_PIZZA;
        }
        else{
            totalBayar -= HARGA_PIZZA;
        }
        TotBayar.setText(String.valueOf(totalBayar));
    }//GEN-LAST:event_PizzaActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JTextField AlamatField;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JPanel DataCustomer;
    private javax.swing.JTextArea DataPesanan;
    private javax.swing.JPanel DataPesananPanel;
    private javax.swing.JLabel HargaPiza;
    private javax.swing.JLabel HargaSpagheti;
    private javax.swing.JLabel HargaSteak;
    private java.awt.Label LabelTItle;
    private javax.swing.JLabel Nama;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NoTelp;
    private javax.swing.JTextField NoTelpField;
    private javax.swing.JPanel PilihMenu;
    private javax.swing.JCheckBox Pizza;
    private javax.swing.JCheckBox Spagheti;
    private javax.swing.JCheckBox Steak;
    private javax.swing.JTextField TotBayar;
    private javax.swing.JLabel TotalBayar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
